name: Build SPA and publish to /public

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/build-frontend.yml"
  workflow_dispatch:

# allow the workflow to commit back to the repo
permissions:
  contents: write

# avoid overlapping runs per branch
concurrency:
  group: build-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # needed to commit back
          persist-credentials: true

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps & build (frontend/)
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Replace /public with frontend/dist
        run: |
          rm -rf public
          mkdir -p public
          cp -R frontend/dist/. public/

      - name: Commit & push updated /public (on main)
        # allow push on normal commits AND manual dispatches
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          if [[ -n "$(git status --porcelain -- public)" ]]; then
            git add public
            git commit -m "chore(frontend): update public from ${GITHUB_SHA::7}"
            git push
          else
            echo "No changes to publish."
          fi
