name: Build SPA and publish to /public

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/build-frontend.yml"
      
permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
      VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
      VITE_AUTH0_AUDIENCE: ${{ secrets.VITE_AUTH0_AUDIENCE }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install & build (frontend/)
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Replace /public with frontend/dist
        run: |
          rm -rf public
          mkdir -p public
          cp -R frontend/dist/* public/

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public
            git commit -m "chore(frontend): update public from $GITHUB_SHA"
            git push
          else
            echo "No changes to publish."
          fi
