name: Build SPA and publish to /public

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/build-frontend.yml"
  workflow_dispatch:

# Allow the workflow to push the updated /public back to main
permissions:
  contents: write

# Avoid overlapping runs
concurrency:
  group: build-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps & build (frontend/)
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Replace /public with frontend/dist
        run: |
          rm -rf public
          mkdir -p public
          cp -R frontend/dist/. public/

      - name: Commit & push updated /public (on main)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          if [[ -n "$(git status --porcelain -- public)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public
            git commit -m "chore(frontend): update public from ${GITHUB_SHA::7}"
            git push
          else
            echo "No changes to publish."
          fi
